-- Add new fields to players table
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS sobrenombre TEXT,
  ADD COLUMN IF NOT EXISTS inactivo BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fecha_alta DATE NOT NULL DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS colegio TEXT;
