-- ============================================================
-- 019_seed_clubs.sql
-- Carga masiva de clubes URBA con dirección y sede por defecto
-- Fuente: clubes_urba.csv (limpiado y normalizado)
-- ============================================================
--
-- CÓMO FUNCIONA EL maps_url:
-- Se genera automáticamente como https://maps.google.com/?q=<dirección>
-- con espacios reemplazados por +. Al tocar el ícono 📍 en la app
-- abre Google Maps buscando esa dirección. Sin API key necesaria.
-- Para una geolocalización exacta (pin) se puede editar después
-- pegando manualmente la URL corta de Google Maps (ej: goo.gl/maps/...)
--
-- NOTA: Clubes sin dirección verificable tienen address = NULL.
-- Se pueden completar desde /admin/clubs cuando se consiga el dato.
-- ============================================================

WITH inserted AS (
  INSERT INTO opponent_clubs (name, active)
  VALUES
    ('Albatros', true),
    ('Almafuerte', true),
    ('Areco', true),
    ('Argentino', true),
    ('Lanús', true),
    ('Alumni', true),
    ('Atlético y Progreso', true),
    ('Atlético del Rosario', true),
    ('Banco Nación', true),
    ('Banco Hipotecario', true),
    ('Belgrano Athletic', true),
    ('Beromama', true),
    ('Buenos Aires CRC', true),
    ('Centro Naval', true),
    ('Atlético Chascomús', true),
    ('Ciudad de Buenos Aires', true),
    ('Ciudad de Campana', true),
    ('Champagnat', true),
    ('CUBA', true),
    ('CASI', true),
    ('Curupayti', true),
    ('DAOM', true),
    ('Delta', true),
    ('Deportiva Francesa', true),
    ('Don Bosco', true),
    ('El Retiro', true),
    ('Gimnasia y Esgrima BA', true),
    ('G y E de Ituzaingó', true),
    ('Hindú', true),
    ('Hurling', true),
    ('Italiano', true),
    ('La Plata RC', true),
    ('La Salle', true),
    ('Las Cañas', true),
    ('Liceo Militar', true),
    ('Liceo Naval', true),
    ('Lomas Athletic', true),
    ('Los Cedros', true),
    ('Los Matreros', true),
    ('Los Pinos', true),
    ('Los Tilos', true),
    ('Luján', true),
    ('Manuel Belgrano', true),
    ('Mariano Moreno', true),
    ('Monte Grande', true),
    ('Vicente López', true),
    ('Arsenal Zárate', true),
    ('Newman', true),
    ('Obras Sanitarias', true),
    ('Old Georgian', true),
    ('Olivos', true),
    ('Porteño', true),
    ('Pucará', true),
    ('Pueyrredón', true),
    ('Regatas Bella Vista', true),
    ('San Albano', true),
    ('San Andrés', true),
    ('CASA de Padua', true),
    ('San Carlos', true),
    ('San Cirano', true),
    ('San Fernando', true),
    ('SIC', true),
    ('San José', true),
    ('San Luis', true),
    ('San Marcos', true),
    ('San Martín', true),
    ('San Miguel', true),
    ('San Patricio', true),
    ('Sociedad Hebraica', true),
    ('SITAS', true),
    ('St. Brendan''s', true),
    ('Tigre', true),
    ('Universitario de La Plata', true),
    ('C.U. de Quilmes', true),
    ('Vicentinos', true),
    ('Virreyes', true),
    ('Varela Jr.', true),
    ('Del Sur Rugby', true),
    ('Atlético San Andrés', true),
    ('Berisso Rugby', true),
    ('Rivadavia de Lobos', true),
    ('Defensores de Glew', true),
    ('Ezeiza', true),
    ('Floresta', true),
    ('Los Molinos', true),
    ('Marcos Paz', true),
    ('Mercedes', true),
    ('Municipal de Berazategui', true),
    ('PAC General Rodríguez', true),
    ('Tiro Federal Baradero', true),
    ('Tiro Federal San Pedro', true)
  RETURNING id, name
),
-- Tabla de direcciones limpias por club
-- NULL = no hay dirección verificable en el CSV fuente
addr(club_name, address) AS (
  VALUES
    ('Albatros',              'Calle 135 y 515, Barrio José Hernández, La Plata, Buenos Aires'),
    ('Almafuerte',            NULL),
    ('Areco',                 NULL),
    ('Argentino',             NULL),
    ('Lanús',                 'Gral. Ferré y Almeyda, Lanús Este, Buenos Aires'),
    ('Alumni',                'Directorio 1155, Tortuguitas, Buenos Aires'),
    ('Atlético y Progreso',   NULL),
    ('Atlético del Rosario',  'Pasaje Gould 865, Rosario, Santa Fe'),
    ('Banco Nación',          'Fray Luis Beltrán, Ingeniero Pablo Nogués, Buenos Aires'),
    ('Banco Hipotecario',     'Caferatta y Roberto M. Ortiz, Ciudad Celina, Buenos Aires'),
    ('Belgrano Athletic',     'Virrey del Pino 3456, CABA'),
    ('Beromama',              'Dr. Equiza 7010, González Catán, Buenos Aires'),
    ('Buenos Aires CRC',      'Dr. René Favaloro 2500, Victoria, Buenos Aires'),
    ('Centro Naval',          NULL),
    ('Atlético Chascomús',    'Av. Lastra 711, Chascomús, Buenos Aires'),
    ('Ciudad de Buenos Aires',NULL),
    ('Ciudad de Campana',     NULL),
    ('Champagnat',            'Panamericana Km 56.5, Estancias del Pilar, Pilar, Buenos Aires'),
    ('CUBA',                  NULL),
    ('CASI',                  'Roque Sáenz Peña 499, Acassuso, Buenos Aires'),
    ('Curupayti',             'Acassuso 2450, Hurlingham, Buenos Aires'),
    ('DAOM',                  'Varela 1802 esq. Castañares, CABA'),
    ('Delta',                 NULL),
    ('Deportiva Francesa',    'Panamericana Km 42.5, Del Viso, Buenos Aires'),
    ('Don Bosco',             NULL),
    ('El Retiro',             'Solis Garay y Camino del Buen Ayre, Hurlingham, Buenos Aires'),
    ('Gimnasia y Esgrima BA', 'Av. Figueroa Alcorta 5575, CABA'),
    ('G y E de Ituzaingó',    'Coronel Niceto Vega 2298, Ituzaingó, Buenos Aires'),
    ('Hindú',                 'Ruta 202 y Av. Del Golf, Don Torcuato, Buenos Aires'),
    ('Hurling',               NULL),
    ('Italiano',              'Av. Riestra 2770, CABA'),
    ('La Plata RC',           'Camino Parque Centenario entre 495 y 496, Manuel B. Gonnet, Buenos Aires'),
    ('La Salle',              'San Lorenzo 3800, Villa Ballester, Buenos Aires'),
    ('Las Cañas',             'Carlos Pellegrini y Santa Cruz, Cañuelas, Buenos Aires'),
    ('Liceo Militar',         'Av. Márquez 6156, Billinghurst, San Martín, Buenos Aires'),
    ('Liceo Naval',           'Av. Cantilo y Udaondo, CABA'),
    ('Lomas Athletic',        'Arenales 663, Lomas de Zamora, Buenos Aires'),
    ('Los Cedros',            'Ruta 202 y El Centinela, San Miguel, Buenos Aires'),
    ('Los Matreros',          NULL),
    ('Los Pinos',             'Joaquín V. González 250, La Lonja, Pilar, Buenos Aires'),
    ('Los Tilos',             'Calle 21 y 522, La Plata, Buenos Aires'),
    ('Luján',                 'Dr. Real entre Francia y Rivadavia, Luján, Buenos Aires'),
    ('Manuel Belgrano',       'La Pista 1601, Ingeniero Maschwitz, Buenos Aires'),
    ('Mariano Moreno',        'San Luis 1900 esq. Padre Fahy, La Reja, Moreno, Buenos Aires'),
    ('Monte Grande',          'P. Dreyer 3302, Monte Grande, Buenos Aires'),
    ('Vicente López',         'Bartolomé Cruz 1175, Vicente López, Buenos Aires'),
    ('Arsenal Zárate',        'Av. Rivadavia esq. Crucero Gral. Belgrano, Zárate, Buenos Aires'),
    ('Newman',                'Av. de los Constituyentes 7245, Benavidez, Buenos Aires'),
    ('Obras Sanitarias',      'Los Italianos s/n, Loma Verde, Escobar, Buenos Aires'),
    ('Old Georgian',          'Juan María Gutiérrez 3829, CABA'),
    ('Olivos',                'Mariano Pelliza 4550, Munro, Buenos Aires'),
    ('Porteño',               NULL),
    ('Pucará',                'Falucho 766, Burzaco, Buenos Aires'),
    ('Pueyrredón',            NULL),
    ('Regatas Bella Vista',   'Av. Francia 1956, Bella Vista, Buenos Aires'),
    ('San Albano',            'Av. Espora 4920, Burzaco, Buenos Aires'),
    ('San Andrés',            'Italia 1600 y Rivadavia, Benavidez, Buenos Aires'),
    ('CASA de Padua',         'Antezana y Piedrabuena, Merlo Norte, Buenos Aires'),
    ('San Carlos',            'Alejandro Vitale s/n, Pablo Nogués, Malvinas Argentinas, Buenos Aires'),
    ('San Cirano',            'Coronel Domínguez 2897, Villa Celina, Buenos Aires'),
    ('San Fernando',          'Sarmiento y Escalada, San Fernando, Buenos Aires'),
    ('SIC',                   'Av. Blanco Encalada 404, San Isidro, Buenos Aires'),
    ('San José',              'Comodoro Rivadavia 3599, La Lonja, Pilar, Buenos Aires'),
    ('San Luis',              'Calle 520 entre 25 y 29, La Plata, Buenos Aires'),
    ('San Marcos',            'Faro Patagonia y Neuquén, Monte Grande, Buenos Aires'),
    ('San Martín',            'Lope de Vega y Colón, Sáenz Peña, Buenos Aires'),
    ('San Miguel',            'Pardo 5200, San Miguel, Buenos Aires'),
    ('San Patricio',          'Caamaño 924, La Lonja, Pilar, Buenos Aires'),
    ('Sociedad Hebraica',     'Ruta 8 Km 51.5, Pilar, Buenos Aires'),
    ('SITAS',                 'Bergamini y Formosa, El Palomar, Buenos Aires'),
    ('St. Brendan''s',        'A. Palma 3150, Villa Rosa, Pilar, Buenos Aires'),
    ('Tigre',                 'Benito Lynch 1060, Tigre, Buenos Aires'),
    ('Universitario de La Plata', 'Calle 14 y 501, Manuel B. Gonnet, La Plata, Buenos Aires'),
    ('C.U. de Quilmes',       NULL),
    ('Vicentinos',            NULL),
    ('Virreyes',              NULL),
    ('Varela Jr.',            'Ruta Provincial 53 Km 10, Florencio Varela, Buenos Aires'),
    ('Del Sur Rugby',         'Camino de Cintura y Río Matanza, 9 de Abril, Esteban Echeverría, Buenos Aires'),
    ('Atlético San Andrés',   'Ruta 26 y España, Ingeniero Maschwitz, Buenos Aires'),
    ('Berisso Rugby',         'Ruta Prov. 15, Los Talas, Berisso, Buenos Aires'),
    ('Rivadavia de Lobos',    NULL),
    ('Defensores de Glew',    NULL),
    ('Ezeiza',                'Roque Sáenz Peña 1500 esq. JJ Vértiz, Tristán Suárez, Buenos Aires'),
    ('Floresta',              NULL),
    ('Los Molinos',           NULL),
    ('Marcos Paz',            'Ángel Sampietro y Gascón, Marcos Paz, Buenos Aires'),
    ('Mercedes',              'Parque Nuevo, Mercedes, Buenos Aires'),
    ('Municipal de Berazategui', NULL),
    ('PAC General Rodríguez', NULL),
    ('Tiro Federal Baradero', NULL),
    ('Tiro Federal San Pedro','Av. España s/n, San Pedro, Buenos Aires')
)
INSERT INTO club_venues (club_id, name, address, maps_url, is_default)
SELECT
  i.id,
  i.name,                          -- nombre de la sede = nombre del club (sede única por defecto)
  a.address,
  CASE WHEN a.address IS NOT NULL
    THEN 'https://maps.google.com/?q=' || replace(replace(a.address, ' ', '+'), '''', '%27')
    ELSE NULL
  END,
  true                             -- is_default = true
FROM inserted i
LEFT JOIN addr a ON i.name = a.club_name;
